spring:
  kafka:
    listener:
      ack-mode: manual
    streams:
      application-id: ktable-demo
      bootstrap-servers: localhost:9092
      properties:
        processing.guarantee: at_least_once # exactly_once_v2 requiert un broker stable
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: kafkaGroupId
      enable-auto-commit: false # uniquement pour @KafkaListener
      properties:
        spring:
          json:
            trusted:
              packages: com.example.kafka.event

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
